### ISSUE TITLE
遇到一个很奇怪的问题，AlertDialog弹出框里面的输入框，必须点击两次才会弹出输入法

### ISSUE THREAD

**Issue by huaxuanHan** [jenly1314/KingKeyboard#10]
遇到一个很奇怪的问题，AlertDialog弹出框里面的输入框，必须点击两次才会弹出车牌输入法，我看到有hide()方法隐藏键盘，有show()方法显示键盘吗？我给edittext加的focus监听，获取到焦点时显示，失去焦点时隐藏，但是没找到显示键盘的方法

**Comment by jenly1314** [comment]
*  **KingKeyboard** 特意不提供显示键盘的方法，就是怕误用，因为理论上来说无需关心键盘什么时候显示，只要是注册了的EditText，内部就会监听EditText的focus来处理键盘的显示与隐藏。
* app 的 [MainActivity](https://github.com/jenly1314/KingKeyboard/blob/master/app/src/main/java/com/king/keyboard/app/MainActivity.kt) 中也有 **Dialog** 中包含输入框使用 **KingKeyboard** 的代码示例。
* 你可以在 **README** 页下载 **演示App** 体验效果，顺便也可以确认下是 集成步骤的问题 还是没有兼容在 Dialog 中使用的 bug 导致。

**Comment by huaxuanHan** [comment]
我第一次点击的时候确实是获取到焦点了，但是不知道为啥不弹出输入法，点击第二次才弹出输入法，输入框上也会显示全选复制粘贴这些，应该是两次获取到焦点了，明天我测试一下是不是因为Dialog的问题吧，感谢
