### ISSUE TITLE
在横屏对话框情况下，显示键盘会遮挡主输入框及内容，无法查看输入内容

### ISSUE THREAD

**Issue by changcsw** [jenly1314/KingKeyboard#12]
在横屏情况下，对话框内有EditText输入内容，显示键盘会遮盖内容，无法看到输入内容，无法做到想系统那样将输入框顶上去显示输入内容，等输入完成后再回到对话框界面

**Comment by jenly1314** [comment]
你使用方式不对，demo中有dialog的使用示例。
