### ISSUE TITLE
在activity写。弹出dialog，不能操作键盘，被盖住了

### ISSUE THREAD

**Issue by imhappyok** [jenly1314/KingKeyboard#13]

**Comment by jenly1314** [comment]
你使用方式不对，demo中有dialog的使用示例。

**Comment by imhappyok** [comment]
那是把布局放dialog里面，如果10个dialog，不得在里面配10个，我想在一个activity写，该activity的10个dialog都可以直接用，而不是dialog的布局里写



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月21日 18:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jenly1314/KingKeyboard] 在activity写。弹出dialog，不能操作键盘，被盖住了 (Issue #13) |

你使用方式不对，demo中有dialog的使用示例。
