### ISSUE TITLE
RecyclerView里面该怎么使用啊

### ISSUE THREAD

**Issue by f262866551** [jenly1314/KingKeyboard#14]
RecyclerView里面该怎么使用啊

**Comment by jenly1314** [comment]
> RecyclerView里面该怎么使用啊

使用方式一样，没什么区别。

**Comment by f262866551** [comment]
> > RecyclerView里面该怎么使用啊
> 
> 使用方式一样，没什么区别。

我在adapter里面使用输入法弹不出来

**Comment by jenly1314** [comment]
> > > RecyclerView里面该怎么使用啊
> > 
> > 
> > 使用方式一样，没什么区别。
> 
> 我在adapter里面使用输入法弹不出来

如果想判定是否是代码有问题，可以先使用系统输入法，然后再换成 [KingKeyboard](https://github.com/jenly1314/KingKeyboard)，看下二者的区别。
