### ISSUE TITLE
车牌号输入如何从省市键盘切换到字母数字键盘

### ISSUE THREAD

**Issue by ymwm-lxl** [jenly1314/KingKeyboard#5]

**Comment by jenly1314** [comment]
你的需求是什么？如：按键触发，还是代码触发？

**Comment by viosonlee** [comment]
请问有没有分离车牌号的省份和字母数字键盘的方式，我看代码里面字母数字的键盘类型是没有暴露出来的

**Comment by jenly1314** [comment]
> 请问有没有分离车牌号的省份和字母数字键盘的方式，我看代码里面字母数字的键盘类型是没有暴露出来的

车牌的字母键盘故意不暴露出来，因为对于车牌类型的键盘而言，省份和字母都只是车牌键盘的一部分；合起来看才是一个整体。如果想分离，你可以使用自定义类型键盘。至于键盘自定义布局你可以参照车牌键盘的布局。
