### ISSUE TITLE
如何让键盘及EditText显示两个字

### ISSUE THREAD

**Issue by zhiyongzuo** [jenly1314/KingKeyboard#6]
例如键盘及EditText都显示【测试】，android:codes该是什么

**Comment by jenly1314** [comment]
你这个需求可以通过使用自定义的按键值来实现；然后通过设置 **setOnKeyExtraListener** 监听来处理按下自定义按键时的逻辑。

自定义按键值相关范围可参见 **README** 中的一段说明：
> 用户可自定义按键值，primaryCode范围区间为-999 ~ -300时，表示预留可扩展按键值；
> 其中-399~-300区间为功能型按键，使用Special背景色，-999~-400自定义按键为默认背景色。
