### ISSUE TITLE
自定义字体大小无效

### ISSUE THREAD

**Issue by qsxs** [jenly1314/KingKeyboard#7]
自定义keyTextSize和labelTextSize均无效
com.king.keyboard. KingKeyboardView 125行被注释了

**Comment by jenly1314** [comment]
已修复 [a68573b2](https://github.com/jenly1314/KingKeyboard/commit/a68573b2ea3aaeb3282526b41c6ff636e0b6edf4)
你暂时可以先通过 **GitPack** 仓库依赖最新的提交。

**Comment by jenly1314** [comment]
**v1.0.4** 已发布
